### PR TITLE
chore: PAPU-45 inject event into biz-events via http call

### PR DESCRIPTION
**Pull request by Giuseppe-LaManna**
#### List of Changes
- added collection postman with http call to inject events

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by and-mora** [comment]
@Giuseppe-LaManna are variables read from a secure file?

**Comment by and-mora** [comment]
> @Giuseppe-LaManna are variables read from a secure file?

in this case we have already the template defined in the repository?

**Comment by Giuseppe-LaManna** [comment]
> > @Giuseppe-LaManna are variables read from a secure file?
> yes, it is
> in this case we have already the template defined in the repository?
>What do you mean by template? a json with the secure-file env structure?

**Comment by and-mora** [comment]
> What do you mean by template? a json with the secure-file env structure?

yes

**Comment by Giuseppe-LaManna** [comment]
@and-mora  
i added it

**Review by and-mora — APPROVED** [review]

**Pull request merged**
